baseurl: '/'
permalink: pretty
title: 'Aditech IT & Consultancy Services'

google_analytics_id: ""

homepage:
  show_call_box: false

logo:
  # mobile: "images/logo/logo-mobile.svg"
  # desktop: "images/logo/logo.svg"
  mobile: "images/logo/aditech-logo-mobile.svg"
  desktop: "images/logo/aditech-logo.svg"
  desktop_height: "54px"

footer:
  copyright_text: 'Made with :love:'

seo:
  meta_og_title: "Aditech IT & Consultancy Pvt Ltd"
  meta_og_type: "website"
  meta_og_url: "https://aditech.net"
  # meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Aditech is a recruitment and HR consultancy provider. With more than 16 years of experience, we hire across all domains: SAP, Manufacturing, full-stack/front-end/back-end/blockchain developers."
  meta_twitter_card: "summary"
  # meta_twitter_site: "@zerostaticio"
  # meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md